version: "1.0"
stages:
  - clone
  - build
  - test
  - deploy-non-prod
  - deploy-prod
steps:
  main_clone:
    title: Cloning main repository...
    stage: clone
    type: git-clone
    repo: DaleMurugan/codefresh-app
    revision: "${{CF_BRANCH}}"
    git: dale-git

  build:
    title: Building App...
    stage: build
    image: node:4.0
    commands:
      - npm install
      - npm run build
    environment:
      - CI=true

  test:
    title: Running unit tests...
    stage: test
    image: node:14.17.6
    commands:
      - npm run test
    environment:
      - CI=true

  deploy-non-prod:
    title: Deploying Docker Image Non-Prod...
    type: build
    stage: deploy-non-prod
    image_name: codefresh-app
    working_directory: ./
    dockerfile: Dockerfile

  deploy-prod:
    title: Deploying Docker Image Prod...
    type: build
    stage: deploy-prod
    image_name: codefresh-app
    working_directory: ./
    dockerfile: Dockerfile
