version: "1.0"
stages:
  - clone
  - build
  - test
  - deploy-non-prod
  - deploy-prod
steps:
  main_clone:
    title: Cloning main repository...
    stage: clone
    type: git-clone
    repo: DaleMurugan/codefresh-app
    revision: "${{CF_BRANCH}}"
    git: dale-git

  build:
    title: Building App...
    stage: build
    image: node:14.17.6
    commands:
      - ./ci/scripts/alwaysPass.sh

  test:
    title: Running unit tests...
    stage: test
    image: node:14.17.6
    commands:
      - ./ci/scripts/alwaysPass.sh

  deploy-non-prod:
    title: Deploying to non-prod...
    stage: deploy-non-prod
    image: node:14.17.6
    commands:
      - ./ci/scripts/failEveryMonday.sh

  deploy-prod:
    title: Deploying to production...
    stage: deploy-prod
    image: node:14.17.6
    commands:
      - ./ci/scripts/failOnThe11th.sh
