version: "1.0"
stages:
  - clone
  - test
  - build
  - deploy
steps:
  clone:
    title: Cloning main repository...
    stage: clone
    type: git-clone
    repo: "DaleMurugan/codefresh-app"
    revision: "${{CF_BRANCH}}"
    git: "dale-git"

  build:
    title: Building App...
    stage: build
    image: node:14.17.6
    commands:
      - npm install
      - npm run build
    environment:
      - CI=true

  test:
    title: Running unit tests...
    stage: test
    image: node:14.17.6
    commands:
      - npm install
      - npm run build
      - npm run test
    environment:
      - CI=true

  deploy:
    title: Deploying Docker Image...
    type: build
    stage: deploy
    image_name: codefresh-app
    working_directory: ./
    dockerfile: Dockerfile
