version: "1.0"
stages:
  - clone
  - test
  - build
steps:
  Clone:
    title: Cloning main repository...
    stage: clone
    type: git-clone
    repo: "DaleMurugan/codefresh-app"
    revision: "${{CF_BRANCH}}"
    git: "dale-git"
  Tests:
    title: Unit test
    stage: test
    image: node:14.17.6
    commands:
      - npm install
      - npm run test
    environment:
      - CI=true
  Deploy:
    title: Deploying to Docker Image
    type: build
    stage: build
    image_name: codefresh-app
    working_directory: ./
    dockerfile: Dockerfile
