version: "1.0"
stages:
  - clone
  # - build
  - test
  - deploy
steps:
  clone:
    title: Cloning main repository...
    stage: clone
    type: git-clone
    repo: "DaleMurugan/codefresh-app"
    revision: "${{CF_BRANCH}}"
    git: "dale-git"

  # build:
  #   title: Building app...
  #   stage: build
  #   image: node:14.17.6
  #   commands:
  #     - npm install
  #     - npm run build
  #   environment:
  #     - CI=true
  test:
    title: Conducting unit tests...
    stage: test
    image: node:14.17.6
    commands:
      - npm install
      - npm run test

  deploy:
    title: Building Docker Image...
    type: build
    stage: deploy
    image_name: codefresh-app
    working_directory: ./
    dockerfile: Dockerfile
