version: "1.0"
stages:
  - clone
  - test
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: clone
    type: git-clone
    repo: "DaleMurugan/codefresh-app"
    revision: "${{CF_BRANCH}}"
    git: "dale-git"
  MyUnitTests:
    title: Unit test
    stage: test
    image: node:8.16
    commands:
      - npm install
    environment:
      - CI=true
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    commands:
      - npm build
